[project]
name = "uv-workspace-example"
version = "0.1"
dependencies = ["server", "greeter"]
requires-python = ">= 3.12"

[tool.uv]
dev-dependencies = []

[tool.uv.sources]
server = { workspace = true }
greeter = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]
