[project]
name = "server"
version = "0.1.0"
description = ""
dependencies = ["greeter" ]
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv]
dev-dependencies = []

[tool.uv.sources]
greeter = { workspace = true }
